import { MaterialTypography, MaterialPalette, MaterialText } from "@material";
import { AppStyle } from "../style.slint";

export component Clock {
    in property <string> hours: "00";
    in property <string> minutes: "00";
    in property <string> date: "";

    VerticalLayout {
        alignment: center;

        // Clock with overlap
        VerticalLayout {
            spacing: - (AppStyle.clock-font-size * 0.3 * 1px);
            Text {
                text: root.hours;
                font-size: AppStyle.clock-font-size * 1px;
                font-weight: AppStyle.clock-font-weight;
                font-family: AppStyle.clock-font-family;
                color: MaterialPalette.primary;
                horizontal-alignment: center;
                letter-spacing: -5px;
            }

            Text {
                text: root.minutes;
                font-size: AppStyle.clock-font-size * 1px;
                font-weight: AppStyle.clock-font-weight;
                font-family: AppStyle.clock-font-family;
                color: MaterialPalette.secondary;
                horizontal-alignment: center;
                letter-spacing: -5px;
            }
        }

        Rectangle {
            height: 20px;
        }

        // Date
        MaterialText {
            text: root.date;
            style: MaterialTypography.headline-small;
            color: MaterialPalette.on-background.with-alpha(0.8);
            horizontal-alignment: center;
        }
    }
}
