import {
    ModalBottomSheet,
    MaterialPalette,
    MaterialTypography,
    MaterialText,
    OutlineIconButton,
} from "@material";

component PowerOption {
    in property <image> icon;
    in property <string> text;

    callback clicked();

    VerticalLayout {
        spacing: 12px;
        alignment: center;

        HorizontalLayout {
            alignment: center;

            OutlineIconButton {
                icon: root.icon;
                width: 64px;
                height: 64px;
                clicked => {
                    root.clicked();
                }
            }
        }

        MaterialText {
            text: root.text;
            style: MaterialTypography.label-large;
            color: MaterialPalette.on-surface;
            horizontal-alignment: center;
        }
    }
}

export component PowerBottomSheet inherits ModalBottomSheet {
    callback shutdown();
    callback reboot();
    callback sleep();
    callback hibernate();

    height: 220px;

    VerticalLayout {
        padding: 24px;
        spacing: 24px;
        alignment: center;

        MaterialText {
            text: "Power Options";
            style: MaterialTypography.title-medium;
            color: MaterialPalette.on-surface-variant;
            horizontal-alignment: center;
        }

        HorizontalLayout {
            alignment: center;
            spacing: 32px;

            PowerOption {
                text: "Sleep";
                icon: @image-url("../icons/bedtime.svg");
                clicked => {
                    root.sleep();
                    root.close();
                }
            }

            PowerOption {
                text: "Hibernate";
                icon: @image-url("../icons/mode_standby.svg");
                clicked => {
                    root.hibernate();
                    root.close();
                }
            }

            PowerOption {
                text: "Restart";
                icon: @image-url("../icons/restart_alt..svg");
                clicked => {
                    root.reboot();
                    root.close();
                }
            }

            PowerOption {
                text: "Shut down";
                icon: @image-url("../icons/power_settings.svg");
                clicked => {
                    root.shutdown();
                    root.close();
                }
            }
        }

        Rectangle {
            height: 20px;
        }
    }
}
